// アプリ内で表示する文言は、このファイルからまとめて変更できます。
export const UI_TEXT = {
  common: {
    appName: 'Project Slow Life',
    pageTitle: 'Slow Life Blocks',
    self: 'あなた',
    leave: '退出',
    players: '参加メンバー',
    close: '閉じる',
    loading: '接続中',
  },
  entry: {
    category: 'PUZZLE',
    title: 'スローライフPUZZLE',
    description: '名前を決めたら、部屋へ向かいましょう。',
    nameLabel: 'あなたの名前',
    namePlaceholder: '例：れん（',
    nameHint: '部屋のメンバーに表示される名前です。',
    next: '次へ',
    player: 'プレイヤー',
    edit: '変更',
    roomModeLabel: '部屋への入り方',
    createRoomTab: '部屋を作る',
    joinRoomTab: '部屋に参加',
    createRoomTitle: '新しい部屋を作る',
    joinRoomTitle: '部屋に参加する',
    createRoomDescription: '仲間に伝える合言葉を決めてください。',
    joinRoomDescription: '仲間から教えてもらった合言葉を入力してください。',
    roomIdLabel: '合言葉',
    roomIdSupplement: '',
    roomIdPlaceholder: '例：スローライフ',
    roomIdHint: '',
    createRoomSubmit: '部屋を作成',
    joinRoomSubmit: '部屋に参加',
  },
  lobby: {
    category: 'WAITING ROOM',
    title: '仲間を待っています',
    roomIdLabel: '合言葉 / ルームID',
    roomIdHint: 'この合言葉を仲間に伝えてください',
    start: 'Play',
    waitingForHost: 'ホストの開始を待っています',
    hostBadge: 'HOST',
  },
  game: {
    roomLabel: 'ROOM',
    membersCategory: 'ROOM MEMBERS',
    showPlayers: '参加メンバーを表示',
    reconnecting: '再接続待ち',
    turnBadge: 'TURN',
    score: 'Score',
    clear: 'Clear',
    turn: 'Turn',
    finished: 'ゲーム終了',
    yourTurn: 'あなたのターンです',
    playerTurn: (name) => `${name}さんのターンです`,
    boardLabel: '共有ゲーム盤面',
    handTitle: '共有の手札',
    rotated: 'ピースを回転しました。',
    placementCancelled: '配置をキャンセルしました。',
    cannotPlace: 'その位置には配置できません。',
    checkingPlacement: '配置を確認しています…',
    dragHelp: '盤面へドラッグしてください。スペースキーまたは2本目の指で回転できます。',
  },
  result: {
    title: 'ゲーム終了',
    teamScore: 'TEAM SCORE',
    description: 'みんなでひとつの盤面を完成させました。',
    clearedLines: '消去ライン',
    totalTurns: '合計ターン',
    playerCount: '参加人数',
    rematch: 'もう一度遊ぶ',
    returnToLobby: 'ロビーに戻る',
    reconnectNotice: '再戦するには全員の再接続を待ってください。',
    waitingForHost: 'ホストの操作を待っています',
  },
};

export const ERROR_TEXT = {
  nameRequired: '名前を入力してください。',
  nameTooLong: (max) => `名前は${max}文字以内で入力してください。`,
  roomIdRequired: '合言葉を入力してください。',
  roomIdTooShort: (min) => `合言葉は${min}文字以上で入力してください。`,
  roomIdTooLong: (max) => `合言葉は${max}文字以内で入力してください。`,
  roomIdLength: (min, max) => `合言葉は${min}～${max}文字で入力してください。`,
  roomExists: 'その合言葉の部屋はすでに存在します。',
  roomNotFound: 'その合言葉の部屋は見つかりません。',
  roomAlreadyPlaying: 'この部屋はすでにゲームを開始しています。',
  roomFull: (max) => `この部屋は${max}人で満員です。`,
  nameTaken: '同じ名前のプレイヤーが参加しています。',
  sessionNotFound: '復帰できるセッションがありません。',
  sessionInUse: 'このプレイヤーはすでに接続しています。',
  notInRoom: '参加中の部屋がありません。',
  onlyHostCanStart: 'ゲームを開始できるのはホストだけです。',
  gameAlreadyStarted: 'ゲームはすでに開始しています。',
  gameNotFound: '参加中のゲームがありません。',
  onlyHostCanOperate: 'この操作を行えるのはホストだけです。',
  gameNotFinished: 'ゲーム終了後に操作できます。',
  playerDisconnected: '再接続待ちのプレイヤーがいます。',
  gameFinished: 'このゲームは終了しています。',
  notYourTurn: '現在はあなたのターンではありません。',
  invalidMove: '配置情報が正しくありません。',
  pieceNotFound: '選択したピースは手札にありません。',
  cannotPlace: 'その位置には配置できません。',
  requestTimeout: 'サーバーに接続できませんでした。もう一度お試しください。',
  network: '通信エラーが発生しました。',
  server: 'サーバーでエラーが発生しました。',
};

export const GAME_TEXT = {
  playerTurn: (name) => `${name}さんのターンです。`,
  noPlayers: 'プレイヤーがいません。',
  noPlaceablePieces: '置けるピースがなくなりました。',
};
